# GravityBridge Sponsorship Channels
# ==================================

github: Arora-Sir
patreon: # (not configured)
buy_me_a_coffee: # (not configured)
custom: ['https://paypal.me/arorasir', 'upi://pay?pa=mohit1998arora@yescred&pn=Mohit%20Arora&cu=INR']
