# GravityBridge Sponsorship Channels
# ==================================

github: Arora-Sir
custom: ['upi://pay?pa=a.mohit1998@okhdfcbank&pn=Mohit%20Arora&cu=INR', 'upi://pay?pa=mohit1998arora@yescred&pn=Mohit%20Arora&cu=INR']
